name: mafia-environment
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - rise
  - ffmpeg
  - pip:
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - RISE
    - ipywidgets
    - manim

